/*
  SPDX-License-Identifier: GPL-3.0-or-later
  MNT Pocket Reform Keyboard/Trackball Controller Firmware for RP2040
  Copyright 2021-2024 MNT Research GmbH (mntre.com)
*/

#include "usb_hid_keys.h"

#define MATRIX_DEFAULT_ROW_1 KEY_GRAVE, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_ESC
#define MATRIX_DEFAULT_ROW_2 KEY_TAB, KEY_APOSTROPHE, KEY_COMMA, KEY_DOT, KEY_P, KEY_Y, KEY_F, KEY_G, KEY_C, KEY_R, KEY_L, KEY_EQUAL
#define MATRIX_DEFAULT_ROW_3 KEY_LEFTCTRL, KEY_A, KEY_O, KEY_E, KEY_U, KEY_I, KEY_D, KEY_H, KEY_T, KEY_N, KEY_S, KEY_MINUS
#define MATRIX_DEFAULT_ROW_4 KEY_LEFTSHIFT, KEY_SEMICOLON, KEY_Q, KEY_J, KEY_K, KEY_X, KEY_B, KEY_M, KEY_W, KEY_V, KEY_Z, KEY_ENTER
#define MATRIX_DEFAULT_ROW_5 KEY_COMPOSE, KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_LEFTALT, KEY_LEFTMETA, KEY_SPACE, KEY_SLASH, KEY_LEFT, KEY_DOWN, KEY_UP, KEY_RIGHT, KEY_BACKSLASH

// Every line of `matrix` is a row of the keyboard, starting from the top.
// Check keyboard.h for the definitions of the default rows.
uint8_t matrix[KBD_MATRIX_SZ] = {
  MATRIX_DEFAULT_ROW_1,
  MATRIX_DEFAULT_ROW_2,
  MATRIX_DEFAULT_ROW_3,
  MATRIX_DEFAULT_ROW_4,
  MATRIX_DEFAULT_ROW_5
};

#define MATRIX_HYPER_ROW_1 KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12
#define MATRIX_HYPER_ROW_2 KEY_NONE, KEY_MEDIA_VOLUMEDOWN, KEY_MEDIA_MUTE, KEY_MEDIA_VOLUMEUP, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE, KEY_HOME, KEY_PAGEUP, KEY_NONE, KEY_NONE
#define MATRIX_HYPER_ROW_3 KEY_NONE, KEY_MEDIA_PREVIOUSSONG, KEY_MEDIA_PLAYPAUSE, KEY_MEDIA_NEXTSONG, KEY_NONE, KEY_NONE, KEY_DELETE, KEY_BACKSPACE, KEY_END, KEY_PAGEDOWN, KEY_NONE, KEY_NONE
#define MATRIX_HYPER_ROW_4 MATRIX_DEFAULT_ROW_4
#define MATRIX_HYPER_ROW_5 MATRIX_DEFAULT_ROW_5

// When holding down HYPER
uint8_t matrix_fn[KBD_MATRIX_SZ] = {
    MATRIX_HYPER_ROW_1,
    MATRIX_HYPER_ROW_2,
    MATRIX_HYPER_ROW_3,
    MATRIX_HYPER_ROW_4,
    MATRIX_HYPER_ROW_5
};
